const attributors = [
  {
    number: "M1",
    attributor: "NASA,  ESA,  J. Hester and A. Loll (Arizona State University)",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=516106",
  },
  {
    number: "M2",
    attributor: "ESA/Hubble",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=77703345",
  },
  {
    number: "M3",
    attributor: "Adam Block/Mount Lemmon SkyCenter/University of Arizona",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=94663247",
  },
  {
    number: "M4",
    attributor: "ESO Imaging Survey",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=94663247",
  },
  {
    number: "M5",
    attributor: "Chuck Ayoub",
    license: "CC0",
    source: "https://commons.wikimedia.org/w/index.php?curid=164859140",
  },
  {
    number: "M6",
    attributor: "Giuseppe Donatiello from Oria (Brindisi)  Italy",
    license: "CC0",
    source: "https://commons.wikimedia.org/w/index.php?curid=98058374",
  },
  {
    number: "M7",
    attributor: "ESO",
    license: "CC BY 3.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=31346316",
  },
  {
    number: "M8",
    attributor: "ESO/VPHAS+ team",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=30759954",
  },
  {
    number: "M9",
    attributor: "NASA & ESA",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=20197163",
  },
  {
    number: "M10",
    attributor: "Manfred Höcherl",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=97138684",
  },
  {
    number: "M11",
    attributor: "ESO",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=35836207",
  },
  {
    number: "M12",
    attributor: "Adam Block",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=97541836",
  },
  {
    number: "M13",
    attributor: "Chuck Ayoub",
    license: "CC0",
    source: "https://commons.wikimedia.org/w/index.php?curid=163946870",
  },
  {
    number: "M14",
    attributor: "NOIRLAB / NSF / AURA",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=95270167",
  },
  {
    number: "M15",
    attributor: "Ngc1535",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=45659020",
  },
  {
    number: "M16",
    attributor: "Chuck Ayoub",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=7338740",
  },
  {
    number: "M17",
    attributor: "ESO/INAF-VST/OmegaCAM, Acknowledgement: OmegaCen/Astro-WISE/Kapteyn",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=26367295",
  },
  {
    number: "M18",
    attributor: "Fabian Rodriguez Frustaglia",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=95657047",
  },
  {
    number: "M19",
    attributor: "Doug Williams  REU Program / NOIRLAB / NSF / AURA",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=95555344",
  },
  {
    number: "M20",
    attributor: "Starhopper",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=65478970",
  },
  {
    number: "M21",
    attributor: "Rick Saunders",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=95611628",
  },
  {
    number: "M22",
    attributor: "ESA/Hubble & NASA",
    license: "Public Domein",
    source: "https://commons.wikimedia.org/w/index.php?curid=39499950",
  },
  {
    number: "M23",
    attributor: "Chuck Ayoub",
    license: "CC0",
    source: "https://commons.wikimedia.org/w/index.php?curid=163786299",
  },
  {
    number: "M24",
    attributor: "Roberto Colombari",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=94466196",
  },
  {
    number: "M25",
    attributor: "Starhopper",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=65487989",
  },
  {
    number: "M26",
    attributor: "Hillary Mathis,  Vanessa Harvey REU program/NOIRLab/NSF/AURA ",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=94750717",
  },
  {
    number: "M27",
    attributor: "REU program/NOIRLab/NSF/AURA",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=116906359",
  },
  {
    number: "M28",
    attributor: "NASA, ESA, STScI, R. Buonanno (U. di Roma Tor Vergata), K. Gebhardt (U. of Texas at Austin), J. Grindlay (Harvard U.), and F. Ferraro (U. di Bologna) ",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=63522029",
  },
  {
    number: "M29",
    attributor: "Veryoldphotons",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=94410606",
  },
  {
    number: "M30",
    attributor: "NASA/ESA",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=95946727",
  },
  {
    number: "M31",
    attributor: "Luc Viatour",
    license: "CC BY-SA 2.5",
    source: "https://commons.wikimedia.org/w/index.php?curid=150485855",
  },
  {
    number: "M32",
    attributor: "Fabrizio Francione",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=96002765",
  },
  {
    number: "M33",
    attributor: "ESO",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=34571682",
  },
  {
    number: "M34",
    attributor: "Jim Mazur",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=96267389",
  },
  {
    number: "M35",
    attributor: "Not mentioned (2MASS)",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/wiki/File:M35atlas.jpg",
  },
  {
    number: "M36",
    attributor: "Not mentioned (2MASS)",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/wiki/File:M36_2mass.jpg",
  },
  {
    number: "M37",
    attributor: "Jim Mazur",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=96810053",
  },
  {
    number: "M38",
    attributor: "Miguel Garcia",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=38532925",
  },
  {
    number: "M39",
    attributor: "Jim Mazur",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=96267497",
  },
  {
    number: "M40",
    attributor: "NOIRLab/NSF/AURA",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=137747383",
  },
  {
    number: "M41",
    attributor: "NOIRLab / NSF / AURA",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=96367172",
  },
  {
    number: "M42",
    attributor: "NASA, ESA, M. Robberto (STScI/ESA), and the Hubble Orion Treasury Project Team",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=1164360",
  },
  {
    number: "M43",
    attributor: "NASA, ESA, M. Robberto (STScI/ESA), and the Hubble Orion Treasury Project Team",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=2522052",
  },
  {
    number: "M44",
    attributor: "Chuck Ayoub",
    license: "CC0",
    source: "https://commons.wikimedia.org/w/index.php?curid=163699680",
  },
  {
    number: "M45",
    attributor: "NASA, ESA, AURA/Caltech, and Palomar Observatory. Science team: D. Soderblom & E. Nelan (STScI), F. Benedict & B. Arthur (U. Texas), B. Jones (Lick Observatory).",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=7805481",
  },
  {
    number: "M46",
    attributor: "Jose Luis Martinez",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=38795641",
  },
  {
    number: "M47",
    attributor: "NOIRLab / NSF / AURA",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=108042386",
  },
  {
    number: "M48",
    attributor: "Jim Mazur",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=108284859",
  },
  {
    number: "M49",
    attributor: "NOIRLAB / NSF / AURA",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=108048366",
  },
  {
    number: "M50",
    attributor: "Jim Mazur",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=108284979",
  },
  {
    number: "M51",
    attributor: "NASA and ESA",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=3863746",
  },
  {
    number: "M52",
    attributor: "Not mentioned (2MASS)",
    license: "Public Domain ",
    source: "https://commons.wikimedia.org/w/index.php?curid=5873581",
  },
  {
    number: "M53",
    attributor: "Sloan Digital Sky Survey",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=76139055",
  },
  {
    number: "M54",
    attributor: "ESA/Hubble & NASA",
    license: "CC BY 3.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=17288442",
  },
  {
    number: "M55",
    attributor: "ESO/J. Emerson/VISTA",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=19381930",
  },
  {
    number: "M56",
    attributor: "NASA, STScl",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=4538592",
  },
  {
    number: "M57",
    attributor: "ESA/Webb, NASA, CSA, M. Barlow, N. Cox, R. Wesson",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=136314581",
  },
  {
    number: "M58",
    attributor: "Adam Block/Mount Lemmon SkyCenter/University of Arizona",
    license: "CC BY-SA 3.0 us",
    source: "https://commons.wikimedia.org/w/index.php?curid=20446011",
  },
  {
    number: "M59",
    attributor: "ESA/Hubble",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=79245450",
  },
  {
    number: "M60",
    attributor: "NASA, ESA, CXC, and J. Strader (Michigan State University)",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=28850575",
  },
  {
    number: "M61",
    attributor: "ESA/Hubble",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=32448499",
  },
  {
    number: "M62",
    attributor: "ESA/Hubble",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=78047240",
  },
  {
    number: "M63",
    attributor: "NASA/ESA - The Hubble Legacy Archive (HLA): STScI, ST-ECF  and CADC-zoranknez (Aladin software)",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=54553490",
  },
  {
    number: "M64",
    attributor: "Judy Schmidt from USA - NGC 4826",
    license: "CC BY 2.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=88116433",
  },
  {
    number: "M65",
    attributor: "ESA/Hubble & NASA",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=30450382",
  },
  {
    number: "M66",
    attributor: "ESO",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=6651180",
  },
  {
    number: "M67",
    attributor: "Jim Mazur",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=108285022",
  },
  {
    number: "M68",
    attributor: "NASA, STScl",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=4490763",
  },
  {
    number: "M69",
    attributor: "ESA/Hubble & NASA",
    license: "CC BY 3.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=21858240",
  },
  {
    number: "M70",
    attributor: "ESA/Hubble & NASA",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=19026450",
  },
  {
    number: "M71",
    attributor: "ESA/Hubble and NASA",
    license: "CC BY 3.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=11335437",
  },
  {
    number: "M72",
    attributor: "NASA, STScl",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=4491163",
  },
  {
    number: "M73",
    attributor: "Digitized Sky Survey 2 - Wikisky",
    license: "CC BY-SA 3.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=108491019",
  },
  {
    number: "M74",
    attributor: "ESO/PESSTO/S. Smartt",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=28062885",
  },
  {
    number: "M75",
    attributor: "ESA/Hubble",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=78269357",
  },
  {
    number: "M76",
    attributor: "Göran Nilsson,  Wim van Berlo & The Liverpool Telescope",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=63294916",
  },
  {
    number: "M77",
    attributor: "NASA, ESA & A. van der Hoeven",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=25328266",
  },
  {
    number: "M78",
    attributor: "ESO/Igor Chekalin",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=13365630",
  },
  {
    number: "M79",
    attributor: "ESA/Hubble",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=64893872",
  },
  {
    number: "M80",
    attributor: "NASA, The Hubble Heritage Team,  STScI,  AURA ",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=6449278",
  },
  {
    number: "M81",
    attributor: "NASA, ESA,  and The Hubble Heritage Team (STScI/AURA)",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=2173424",
  },
  {
    number: "M82",
    attributor: "NASA, ESA,  and The Hubble Heritage Team (STScI/AURA)",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=797295",
  },
  {
    number: "M83",
    attributor: "CTIO/NOIRLab/DOE/NSF/AURA Image processing: T.A. Rector (University of Alaska Anchorage/NSF NOIRLab),  D. de Martin (NSF NOIRLab) & M. Zamani (NSF NOIRLab)",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=156389522",
  },
  {
    number: "M84",
    attributor: "ESA/Hubble",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=40721382",
  },
  {
    number: "M85",
    attributor: "ESA/Hubble",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=76338705",
  },
  {
    number: "M86",
    attributor: "ESA/Hubble",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=82450479",
  },
  {
    number: "M87",
    attributor: "NASA, STScl",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=7598267",
  },
  {
    number: "M88",
    attributor: "Ngc1535",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=126822139",
  },
  {
    number: "M89",
    attributor: "ESA/Hubble",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=75838622",
  },
  {
    number: "M90",
    attributor: "Judy Schmidt from USA - NGC 4569",
    license: "CC BY 2.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=87984450",
  },
  {
    number: "M91",
    attributor: "NASA, ESA,  and J. Lee (California Institute of Technology)",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=108923220",
  },
  {
    number: "M92",
    attributor: "NASA, STScl",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=4550168",
  },
  {
    number: "M93",
    attributor: "Sergio Eguivar",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=109294041",
  },
  {
    number: "M94",
    attributor: "R Jay Gabany (Blackbird Obs.)",
    license: "CC BY-SA 3.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=28029444",
  },
  {
    number: "M95",
    attributor: "ESA/Hubble",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=73467259",
  },
  {
    number: "M96",
    attributor: "ESO/Oleg Maliy",
    license: "CC BY 3.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=17122096",
  },
  {
    number: "M97",
    attributor: "NOIRLab / NSF / AURA",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=108963954",
  },
  {
    number: "M98",
    attributor: "ESO. Acknowledgements: Flickr user jbarring",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=51140486",
  },
  {
    number: "M99",
    attributor: "Adam Block/Mount Lemmon SkyCenter/University of Arizona",
    license: "CC BY-SA 3.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=118284387",
  },
  {
    number: "M100",
    attributor: "ESO",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=27491069",
  },
  {
    number: "M101",
    attributor: "ESA/Hubble",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=36216331",
  },
  {
    number: "M103",
    attributor: "Jim Mazur",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=109293623",
  },
  {
    number: "M104",
    attributor: "ESA/Hubble",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=163685254",
  },
  {
    number: "M105",
    attributor: "ESA/Hubble",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=75648413",
  },
  {
    number: "M106",
    attributor: "NASA, ESA,  the Hubble Heritage Team (STScI/AURA), and R. Gendler (for the Hubble Heritage Team), J. GaBany ",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=24510083",
  },
  {
    number: "M107",
    attributor: "NASA, STScl",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=4491712",
  },
  {
    number: "M108",
    attributor: "Sloan Digital Sky Survey",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=76111734",
  },
  {
    number: "M109",
    attributor: "KPNO/NOIRLab/NSF/AURA/George Hatfield and Flynn Haase",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=139416904",
  },
  {
    number: "M110",
    attributor: "ESA, Not So Dead After All",
    license: "CC BY 2.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=119295663",
  },
  {
    number: "Sun",
    attributor: "Matúš Motlo",
    license: "CC BY-SA 4.0,",
    source: "https://commons.wikimedia.org/w/index.php?curid=94650721",
  },
  {
    number: "Moon",
    attributor: "Gregory H. Revera",
    license: "CC BY-SA 3.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=11901243",
  },
  {
    number: "Mercury",
    attributor: "NASA/Johns Hopkins University/Arizona State University/Carnegie Institution of Washington",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=83618472"
  },
  {
    number: "Venus",
    attributor: "NASA/Johns Hopkins University/Carnegie Institution of Washington",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=2450357",
  },
  {
    number: "Earth",
    attributor: "NASA/Apollo 17 crew; taken by either Harrison Schmitt or Ron Evans ",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=43894484",
  },
  {
    number: "Mars",
    attributor: "evin Gill from Los Angeles, CA, United States",
    license: "CC BY 2.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=114594182",
  },
  {
    number: "Jupiter",
    attributor: "NASA/STSCI (S.T.A.R.S) ",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=159176801",
  },
  {
    number: "Saturn",
    attributor: "NASA / JPL / Space Science Institute",
    license: "Public Domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=7228953",
  },
  {
    number: "Uranus",
    attributor: "Ardenau4",
    license: "CC0",
    source: "https://commons.wikimedia.org/w/index.php?curid=143666922",
  },
  {
    number: "Neptune",
    attributor: "NASA / Voyager 2 / PDS / OPUS / Ardenau4",
    license: "CC0",
    source: "https://commons.wikimedia.org/w/index.php?curid=143615671",
  },
];

const container = document.getElementById("container");

attributors.forEach(item => {
      const line = document.createElement("div");
      line.textContent = `${item.number}: ${item.attributor}, ${item.license}, `;
      
      const link = document.createElement("a");
      link.href = item.source;
      link.textContent = "source";
      link.target = "_blank";

      line.appendChild(link);
      container.appendChild(line);
    });
